import { configured, supabase } from "./supabase-app.js";
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function rows(name,sort="date",ascending=true){if(!configured)return[];try{const {data,error}=await supabase.from(name).select('*').order(sort,{ascending});if(error)throw error;return data||[];}catch{return[];}}
const date=v=>{if(!v)return"—";const d=new Date(v+"T00:00:00");return Number.isNaN(d.getTime())?v:d.toLocaleDateString("en-PH",{month:"short",day:"numeric",year:"numeric"})};
const dt=v=>{if(!v)return"—";const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString("en-PH",{month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})};
const dayOrder={Monday:1,Tuesday:2,Wednesday:3,Thursday:4,Friday:5,Saturday:6,Sunday:7};
async function schedule(){const t=document.getElementById("scheduleBody");if(!t)return;const r=(await rows("schedules","day",true)).sort((a,b)=>(dayOrder[a.day]||9)-(dayOrder[b.day]||9)||String(a.start_time).localeCompare(String(b.start_time)));t.innerHTML=r.length?r.map(x=>`<tr><td><strong>${esc(x.day)}</strong></td><td><strong>${esc(x.subject_name)}</strong></td><td>${esc(x.professor)}</td><td>${esc(x.start_time)} – ${esc(x.end_time)}</td><td><span class="platform-badge">${esc(x.platform||"TBA")}</span>${x.meeting_link?`<br><a class="text-link" href="${esc(x.meeting_link)}" target="_blank" rel="noopener">Join class →</a>`:""}</td><td>${esc(x.room||x.notes||"—")}</td></tr>`).join(""):`<tr><td colspan="6"><div class="empty">No semester schedules have been published yet.</div></td></tr>`;}
async function activities(){const t=document.getElementById("activityList");if(!t)return;const filter=document.getElementById("activitySubjectFilter"),search=document.getElementById("activitySearch"),r=await rows("activities","deadline",true);const subs=[...new Set(r.map(x=>x.subject_name).filter(Boolean))].sort();subs.forEach(s=>{const o=document.createElement("option");o.value=s;o.textContent=s;filter?.appendChild(o)});function draw(){const f=filter?.value||"",q=(search?.value||"").toLowerCase();const a=r.filter(x=>(!f||x.subject_name===f)&&(!q||[x.title,x.subject_name,x.professor,x.description].join(" ").toLowerCase().includes(q)));t.innerHTML=a.length?a.map(x=>{const d=x.deadline?new Date(x.deadline):null,n=new Date(),diff=d?d-n:null;let status="NO DEADLINE",cls="status-neutral",when="";if(d&&!Number.isNaN(d.getTime())){if(diff<0){status="OVERDUE";cls="status-overdue";when="Past deadline"}else if(diff<172800000){status="DUE SOON";cls="status-soon";when=`Due in ${Math.max(1,Math.ceil(diff/3600000))}h`}else{status="UPCOMING";cls="status-upcoming";when=`Due in ${Math.ceil(diff/86400000)}d`}}return `<article class="calendar-item"><div class="calendar-date">${esc(dt(x.deadline))}<span class="status-badge ${cls}">${status}</span></div><div><h3>${esc(x.title)}</h3><p><strong>${esc(x.subject_name)}</strong>${x.professor?` • ${esc(x.professor)}`:""}</p><p>${esc(x.description||"")}</p>${x.assigned_date?`<small>Assigned: ${esc(date(x.assigned_date))}</small>`:""}</div><div class="calendar-meta"><strong>${when}</strong>${x.submission_method?`<span>${esc(x.submission_method)}</span>`:""}${x.submission_link?`<a class="btn small primary" href="${esc(x.submission_link)}" target="_blank" rel="noopener">Submit →</a>`:""}${x.attachment_url?`<a class="btn small secondary" href="${esc(x.attachment_url)}" target="_blank" rel="noopener">Attachment →</a>`:""}</div></article>`}).join(""):`<div class="empty">No activities match your search.</div>`}filter?.addEventListener("change",draw);search?.addEventListener("input",draw);draw();}
async function events(){const t=document.getElementById("eventList");if(!t)return;const r=await rows("events","date",true);t.innerHTML=r.length?r.map(x=>`<article class="calendar-item">${x.image_url?`<div style="margin-bottom:12px"><img src="${esc(x.image_url)}" alt="${esc(x.title)} poster" style="width:min(100%,420px);max-height:240px;object-fit:cover;border-radius:16px;border:1px solid var(--line)"></div>`:""}<div class="calendar-date">${esc(date(x.date))}</div><div><h3>${esc(x.title)}</h3><p>${esc(x.description||"")}</p></div><div class="calendar-meta">${esc(x.time||"")}<br>${esc(x.location||"")}${x.link?`<a class="text-link" href="${esc(x.link)}" target="_blank" rel="noopener">Details →</a>`:""}</div></article>`).join(""):`<div class="empty">No upcoming events have been published yet.</div>`;}
async function pup(){const t=document.getElementById("pupList");if(!t)return;const r=await rows("pup_calendar","date",true);t.innerHTML=r.length?r.map(x=>`<article class="calendar-item"><div class="calendar-date">${esc(date(x.date))}</div><div><h3>${esc(x.title)}</h3><p>${esc(x.description||"")}</p></div><div class="calendar-meta"><span>${esc(x.category||"University")}</span></div></article>`).join(""):`<div class="empty">The official PUP calendar has not been uploaded yet.</div>`;}
schedule();activities();events();pup();
